version: '2'
services:
    timesheet-app:
        image: timesheet
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://timesheet-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=timesheet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timesheet-mongodb:
        extends:
            file: mongodb.yml
            service: timesheet-mongodb
