version: '2'
services:
    timesheet-mongodb:
        image: mvertes/alpine-mongo
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/timesheet/mongodb/:/data/db/
